version: '3'

services:
  database:
    container_name: db
    build: ./tmp_db
    environment:
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - BACKUP_FILE=${BACKUP_FILE}
      - MSSQL_BACKUP_DIR=${MSSQL_BACKUP_DIR}
    ports:
      - 2866:1433

  backend:
    container_name: core-api
    build:
      context: ./src
      args:
        - PRIVATE_KEY=${PRIVATE_KEY}
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
    ports:
      - 8000:8000
    volumes:
      - ./caddy_volume:/data
      - ./caddy_config:/config
      - ./src:/usr/src
    depends_on:
      - database
