version: '3'

services:
  database:
    container_name: db
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=Votechain
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    ports:
      - 2866:2866

  backend:
    container_name: core-api
    build:
      context: ./src
      args:
        - PRIVATE_KEY=${PRIVATE_KEY}
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - PORT=8000
      - SMTP_SERVER=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - CORS_FRONTEND=${CORS_FRONTEND}
    ports:
      - 8000:8000
    volumes:
      - ./caddy_volume:/data
      - ./caddy_config:/config
      - ./src:/usr/src
    depends_on:
      - database
