version: '3'

services:
  database:
    container_name: db
    build: ./tmp_db
    ports:
      - 1433:1433
    expose:
      - 1433

  backend:
    container_name: core-api
    build: ./src
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./caddy_volume:/data
      - ./caddy_config:/config
    depends_on:
      - database
