# Generated by Django 3.1.2 on 2020-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(blank=True, db_index=True)),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
