# Generated by Django 3.1.2 on 2020-10-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
