# Generated by Django 3.0.10 on 2020-12-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201205_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.Poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('trail_token', models.UUIDField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Vote'))
            ],
        ),
    ]
