# Generated by Django 3.0.10 on 2020-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201208_1342'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('name', 'poll'), name='UQ_Candidate_name_poll'),
        ),
    ]
