# Generated by Django 3.0.10 on 2021-01-11 15:18

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_1147'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='poll',
            constraint=models.CheckConstraint(check=models.Q(end__gt=django.db.models.expressions.F('start')), name='core_poll_start_end_date_check'),
        ),
    ]
