# Generated by Django 3.0.10 on 2021-01-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210111_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
