# Generated by Django 3.0.10 on 2021-01-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210104_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteIdentificationToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField()),
                ('assigned', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Poll')),
            ],
        ),
    ]
