# Generated by Django 3.0.10 on 2021-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_voteidentificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteidentificationtoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
