# Generated by Django 3.0.10 on 2021-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_voteidentificationtoken_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
