# Generated by Django 3.0.10 on 2021-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_voter_password_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='vote',
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_token',
            field=models.CharField(max_length=512),
        ),
    ]
