# Generated by Django 3.0.10 on 2021-02-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210207_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
